Feature/nex 90 update renamed ui module
oat-sa/extension-tao-datauri pull request #27
Opened 2019-06-03 14:05 UTC by btamas

Update reference to renamed ui module

Dependency:

- [ ] https://github.com/oat-sa/tao-core/pull/2158

2019-06-05 13:09 UTC, ferenckiss89 approved these changes

2019-06-05 13:16 UTC, ferenckiss89 requested changes

2019-06-05 13:16 UTC, ferenckiss89 commented on views/js/controller/base64Converter.js
>  define([
update copyright header pls

2019-06-06 15:33 UTC, krampstudio commented
I'm closing this PR the extension is flagged as deprecated

2019-06-06 15:33 UTC, closed without merging